apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: network-policy-alex
  namespace: namespace-c
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - ipBlock:
        cidr: 10.244.120.79/32
  egress:
  - from:
    - ipBlock:
        cidr: 10.244.120.78/32