kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: network-policy-alex
spec:
  podSelector:
    matchLabels:
      project: namespace-c
  ingress:
  - from:
      - ipBlock:
          cidr: 10.244.130.74/32