apiVersion: apps/v1
kind: Deployment
metadata:
  name: sam-app
  labels:
    app: sam
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sam
  template:
    metadata:
      labels:
        app: sam
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80