apiVersion: apps/v1
kind: Deployment
metadata:
  name: sam2-app
  labels:
    app: sam2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sam2
  template:
    metadata:
      labels:
        app: sam2
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 82