apiVersion: apps/v1
kind: Deployment
metadata:
  name: clover-app
  labels:
    app: clover
    project : namespace-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clover
  template:
    metadata:
      labels:
        app: clover
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80